/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Framework Expansion": "框架扩展",
    "Gives +20% speed per upgrade": "每次升级提供 +20% 速度",
    "Gives +50% more prestige points per upgrade": "每次升级提供 +50% 更多声望点",
    "Gives 1 row and column per upgrade": "每次升级提供 1 行和 1 列",
    "prestige points": "声望点",
    "Quantum Fluctuations": "量子波动",
    "Controlled Fusion": "可控聚变",
    "Controlling Eye": "控制眼",
    "dark points": "黑暗点",
    "Gives +0.01% boost per dark point per upgrade": "每次升级为每个暗点提供 +0.01% 提升",
    "Gives +12% speed per upgrade": "每次升级提供 +12% 速度",
    "Multiplies online dark point gain by 1.2 (base gain of 0.2": "将在线黑暗点增益乘以 1.2（基础增益为 0.2",
    "Mystic Brew": "神秘酿造",
    "Summoning Circle": "召唤圈",
    "You produce dark points while offline": "您在离线时产生黑暗点",
    "Atomic Burst": "原子爆",
    "Explosive Impact": "爆炸冲击",
    "Gives +10% chance per upgrade": "每次升级提供 +10% 几率",
    "Gives +75% speed per upgrade. RGB point cap is based on total RGB upgrades.": "每次升级提供 +75% 的速度。 RGB 点数上限基于 RGB 总升级。",
    "Gives a +0.5% chance per upgrade. Triggers whenever a square is tiered up.": "每次升级提供 +0.5% 的机会。 每当一个方块被分层时触发。",
    "Mega Boost": "顶级提升",
    "Rainbow Rush": "彩虹冲刺",
    "RGB points": "RGB点",
    "Unstable Impact": "不稳定冲击",
    "Unstable Reaction": "不稳定反应",
    "Welcome to Rainbow Haven, where all the rainbows are!": "欢迎来到彩虹天堂，这里有彩虹！",
    "Solar Fusion": "太阳能聚变",
    "Ultra Boost": "终极提升",
    "Congratulations! You have reached the end and wasted your time.": "恭喜！ 你已经走到了尽头，浪费了你的时间。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)s$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^gains a (.+)x multiplier.$/, '获得 $1x 乘数。'],
    [/^Gives (.+) multiplier per upgrade$/, '每次升级提供 $1x 乘数'],
    [/^Gives (.+) chance per upgrade$/, '每次升级提供 $1 几率'],
    [/^Cost: (.+) prestige points\n(.+)Amount: (.+)\n(.+)Harvesting has a (.+) chance to also harvest adjacent squares, if possible.$/, '成本：$1 声望点\n$2数量：$3\n$4如果可能的话，收获有 $5 的几率也收获相邻的方格。'],
    [/^Cost: (.+) prestige points\n(.+)Amount: (.+)\n(.+)Squares have a (.+) chance to give (.+)x more prestige points.$/, '成本：$1 声望点\n$2数量：$3\n$4方块有 $5 的几率提供 $6x 以上的声望点数。'],
    [/^Cost: (.+) prestige points\n(.+)Amount: (.+)\n(.+)Squares have a (.+) chance to gain (.+) level.$/, '成本：$1 声望点\n$2数量：$3\n$4方格有 $5 的几率获得 $6 级。'],
    [/^Cost: (.+) prestige points\n(.+)Amount: (.+)\n(.+)Squares are produced (.+)x faster.$/, '成本：$1 声望点\n$2数量：$3\n$4方块的生产速度提高 $5x。'],
    [/^Cost: (.+) prestige points\n(.+)Amount: (.+)\n(.+)Gives (.+) row and column of squares per upgrade.$/, '成本：$1 声望点\n$2数量：$3\n$4每次升级提供 $5 行和列的方块。'],
    [/^Cost: (.+) prestige points\n(.+)Amount: (.+)\n(.+)Squares give (.+)x more prestige points.$/, '成本：$1 声望点\n$2数量：$3\n$4方块提供 $5x 的声望点数。'],
    [/^Cost: (.+) dark points\n(.+)Amount: (.+)\n(.+)Dark points increase prestige point gain by (.+).$/, '成本：$1 黑暗点\n$2数量：$3\n$4黑暗点增加声望点增益 $5。'],
    [/^Cost: (.+) dark points\n(.+)Amount: (.+)\n(.+)Dark points are produced (.+)x faster.$/, '成本：$1 黑暗点\n$2数量：$3\n$4黑暗点的生成速度提高了 $5x。'],
    [/^Cost: (.+) dark points\n(.+)Amount: (.+)\n(.+)You gain 0.00 dark points per second while online.$/, '成本：$1 黑暗点\n$2数量：$3\n$4您在线时每秒获得 $5 黑暗点。'],
    [/^Cost: (.+) RGB points\n(.+)Amount: (.+)\n(.+)Produces (.+) RGB points per second, up to (.+) RGB points.$/, '成本：$1 RGB点\n$2数量：$3\n$4每秒产生 $5 个 RGB 点，最多 $6 个 RGB 点。'],
    [/^Cost: (.+) RGB points\n(.+)Amount: (.+)\n(.+)Gives a (.+) chance to add (.+) tier to a square that has been affected by$/, '成本：$1 RGB点\n$2数量：$3\n$4有 $5 的几率将受到影响的方格增加 $6 层'],
    [/^Cost: (.+) RGB points\n(.+)Amount: ([\d\.]+) \/ ([\d\.]+)$/, '成本：$1 RGB点\n$2数量：$3\/$4'],
	[/^Gives a (.+) chance per upgrade \(Base trigger chance of (.+)$/, '每次升级提供 $1 的几率（基础触发几率为 $2'],
	[/^has a (.+) chance to affect much more squares.$/, '有 $1 的几率影响更多的方格。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+) RGB points$/, '$1 RGB点'],
	[/^([\d\.]+) dark points$/, '$1 黑暗点'],
	[/^([\d\.]+) prestige points$/, '$1 声望点'],
	[/^([\d\.,]+) prestige points$/, '$1 声望点'],
	[/^([\d\.]+)e([\d\.,]+) prestige points$/, '$1 声望点'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);